[project]
name = "base2stacks-tracker"
description = "Cross-chain bridge tracker between Base Network and Stacks"
authors = ["wkalidev <wkalidev@base2stacks.io>"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.b2s-token]
path = "contracts/b2s-token.clar"
clarity_version = 2
epoch = 2.5

[repl]
costs_version = 2
parser_version = 2
